### ISSUE TITLE
Quicksave which makes the game crash

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#177]
Originally reported by: **JAsmine-ja2 (Bitbucket: [JAsmine-ja2](http://bitbucket.org/JAsmine-ja2), GitHub: [JAsmine-ja2](http://github.com/JAsmine-ja2))**

----------------------------------------

The attached quicksave was created during a battle. Trying to load it results in this error:
![1.jpg](https://bitbucket.org/repo/6zkzG5/images/791242949-1.jpg)

And then lead to a crash with this message:
![2.jpg](https://bitbucket.org/repo/6zkzG5/images/1594631496-2.jpg)

----------------------------------------
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/177

**Comment by derSteFfi** [comment]
Still present on master:
```
Program received signal SIGABRT, Aborted.
0x00007ffff6ca95f8 in raise () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff6ca95f8 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6caaa7a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff6ce805a in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff6ced9a6 in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff6cee18e in _int_free () from /usr/lib/libc.so.6
#5  0x000000000052936c in DeleteAnimationCache(unsigned short, AnimationSurfaceCacheType*) ()
#6  0x00000000005e50eb in DeleteSoldier (s=...) at Build/Tactical/Soldier_Control.cc:707
#7  0x00000000005e4eb9 in CreateSoldierCommon (s=...) at Build/Tactical/Soldier_Control.cc:652
#8  0x00000000005f54a7 in TacticalCreateSoldierFromExisting (existing=0x7fffffffa4c0) at Build/Tactical/Soldier_Create.cc:479
#9  0x000000000049effd in LoadSoldierStructure (f=0x41cec460, savegame_version=99, stracLinuxFormat=false) at Build/SaveLoadGame.cc:1384
#10 0x000000000049d9d9 in LoadSavedGame (save_slot_id=0 '\000') at Build/SaveLoadGame.cc:825
#11 0x00000000004a431b in DoneFadeOutForSaveLoadScreen () at Build/SaveLoadScreen.cc:1332
#12 0x0000000000446a05 in HandleFadeOutCallback () at Build/Fade_Screen.cc:98
#13 0x00000000004a2445 in SaveLoadScreenHandle () at Build/SaveLoadScreen.cc:267
#14 0x000000000044863d in GameLoop () at Build/GameLoop.cc:299
#15 0x00000000006ae50b in MainLoop (msPerGameCycle=25) at sgp/SGP.cc:252
#16 0x00000000006aecb1 in main (argc=2, argv=0x7fffffffe098) at sgp/SGP.cc:515
(gdb) 
```

Also spits out a load of debug info without function names but linked in libraries and this one new information
```
*** Error in `/home/dersteffi/ja2-strat/ja2': double free or corruption (!prev): 0x00000000427ac8a0 ***
```

With a breakpoint in DeleteSoldier (checking for the double free), i can see that it is called twice for this soldier (i added a printf to UnLoadCachedAnimationSurfaces to validate it's the same SoldierID and *pAnimCache):
```
Breakpoint 1, DeleteSoldier (s=...) at Build/Tactical/Soldier_Control.cc:659
659		if (s.sGridNo != NOWHERE)
(gdb) backtrace
#0  DeleteSoldier (s=...) at Build/Tactical/Soldier_Control.cc:659
#1  0x00000000005f6b0d in InternalTacticalRemoveSoldier (s=..., fRemoveVehicle=1 '\001') at Build/Tactical/Soldier_Create.cc:988
#2  0x00000000005f6b54 in TacticalRemoveSoldier (s=...) at Build/Tactical/Soldier_Create.cc:1000
#3  0x00000000005cde7a in TurnSoldierIntoCorpse (s=...) at Build/Tactical/Rotting_Corpses.cc:751
#4  0x00000000005e2f89 in HandleSoldierDeath (pSoldier=0xcab490 <Menptr+66768>, pfMadeCorpse=0x7fffffff99bf "") at Build/Tactical/Soldier_Ani.cc:2946
#5  0x00000000005e3042 in CheckForAndHandleSoldierDeath (pSoldier=0xcab490 <Menptr+66768>, pfMadeCorpse=0x7fffffff99bf "")
    at Build/Tactical/Soldier_Ani.cc:3001
#6  0x00000000005de359 in AdjustToNextAnimationFrame (pSoldier=0xcab490 <Menptr+66768>) at Build/Tactical/Soldier_Ani.cc:447
#7  0x00000000005e6d82 in EVENT_InitNewSoldierAnim (pSoldier=0xcab490 <Menptr+66768>, usNewState=41, usStartingAniCode=6, fForce=1 '\001')
    at Build/Tactical/Soldier_Control.cc:1741
#8  0x00000000005e4ed7 in CreateSoldierCommon (s=...) at Build/Tactical/Soldier_Control.cc:645
#9  0x00000000005f54e7 in TacticalCreateSoldierFromExisting (existing=0x7fffffffa4c0) at Build/Tactical/Soldier_Create.cc:479
#10 0x000000000049effd in LoadSoldierStructure (f=0x41a47a70, savegame_version=99, stracLinuxFormat=false) at Build/SaveLoadGame.cc:1384
#11 0x000000000049d9d9 in LoadSavedGame (save_slot_id=0 '\000') at Build/SaveLoadGame.cc:825
#12 0x00000000004a431b in DoneFadeOutForSaveLoadScreen () at Build/SaveLoadScreen.cc:1332
#13 0x0000000000446a05 in HandleFadeOutCallback () at Build/Fade_Screen.cc:98
#14 0x00000000004a2445 in SaveLoadScreenHandle () at Build/SaveLoadScreen.cc:267
#15 0x000000000044863d in GameLoop () at Build/GameLoop.cc:299
#16 0x00000000006ae54b in MainLoop (msPerGameCycle=25) at sgp/SGP.cc:252
#17 0x00000000006aecf1 in main (argc=2, argv=0x7fffffffe098) at sgp/SGP.cc:515
(gdb) c
Continuing.
called with usSoldierID = 26d, pAnimCache = 0000001a

Breakpoint 1, DeleteSoldier (s=...) at Build/Tactical/Soldier_Control.cc:659
659		if (s.sGridNo != NOWHERE)
(gdb) backtrace
#0  DeleteSoldier (s=...) at Build/Tactical/Soldier_Control.cc:659
#1  0x00000000005e4ef9 in CreateSoldierCommon (s=...) at Build/Tactical/Soldier_Control.cc:652
#2  0x00000000005f54e7 in TacticalCreateSoldierFromExisting (existing=0x7fffffffa4c0) at Build/Tactical/Soldier_Create.cc:479
#3  0x000000000049effd in LoadSoldierStructure (f=0x41a47a70, savegame_version=99, stracLinuxFormat=false) at Build/SaveLoadGame.cc:1384
#4  0x000000000049d9d9 in LoadSavedGame (save_slot_id=0 '\000') at Build/SaveLoadGame.cc:825
#5  0x00000000004a431b in DoneFadeOutForSaveLoadScreen () at Build/SaveLoadScreen.cc:1332
#6  0x0000000000446a05 in HandleFadeOutCallback () at Build/Fade_Screen.cc:98
#7  0x00000000004a2445 in SaveLoadScreenHandle () at Build/SaveLoadScreen.cc:267
#8  0x000000000044863d in GameLoop () at Build/GameLoop.cc:299
#9  0x00000000006ae54b in MainLoop (msPerGameCycle=25) at sgp/SGP.cc:252
#10 0x00000000006aecf1 in main (argc=2, argv=0x7fffffffe098) at sgp/SGP.cc:515
(gdb) c
Continuing.
called with usSoldierID = 26d, pAnimCache = 0000001a

Program received signal SIGSEGV, Segmentation fault.
0x00000000005295f7 in UnLoadCachedAnimationSurfaces (usSoldierID=26, pAnimCache=0xcab800 <Menptr+67648>) at Build/Tactical/Animation_Cache.cc:145
145			if ( pAnimCache->usCachedSurfaces[ cnt ] != EMPTY_CACHE_ENTRY )
(gdb) 
```

the second call of course causes a SIGSEGV because this soldier already was 'deleted'. I'm investigating now, why this is the case.

**Comment by derSteFfi** [comment]
kind of giving up on this one... I do not know enough about the savegame structure of JA2 :)
Interestingly, and maybe part of the problem: jape reports 'Truck', full name Ice Cream Truck, as an active squad member. Is this supposed to be this way? The id of the soldier that is tried to be loaded multiple times is 200 (0xC8).

**Comment by lynxlynxlynx** [comment]
I think Jasmine was playing with mods, so it could be a data bug and now a corrupt save. We should handle it more gracefully in either case though.

Thanks for starting the triage btw!

**Comment by derSteFfi** [comment]
no problem :)
yes, i think this savegame is corrupt, but the way of loading games we have right now also seems quite fragile to me, although this is another topic and would be a huge change and loads of work...
