### ISSUE TITLE
sdl2 crashes

### ISSUE THREAD

**Issue by mgrobelin** [ja2-stracciatella/ja2-stracciatella#364]
Hi guys,
I am running stracciatella with `./ja2 -res 640x480 -fullscreen -debug` as it gives best visual experience on my tv screen. When building with sdl 1.2.15 the fonts look unreadable, so I went over to sdl 2.0.4.

The game starts fine, fonts and everything looks good, but after some hours of play I got bugged: 

1) when using the wire cutter on Drassen airport, it crashed with something like `Assertion failed ... Tactical/PathAI.cc, line 1851`. I managed to work around this crash by bullying through the main gate, so maybe no big deal. But maybe it will crash anytime again using the cutter. It happens, whenever I equip it, right-click and hover the wire cutter icon over the fence. It got red color for a milisecond and then bye-bye.

2) it seems to crashe everytime a certain death animation is involved. Or a sound, I don't know. The log says:

```
2016/07/15 23:01:30 DEBUG   [Event Pump      ] AddGameEvent: Sending Local #4
2016/07/15 23:01:30 DEBUG   [Asserts         ] Reducing attacker busy count..., CODE FROM ANIMATION SHOOT (R) CROUCH ( 28 )
2016/07/15 23:01:30 DEBUG   [Overhead        ] Ending attack, attack count now 1
2016/07/15 23:01:30 DEBUG   [Animations      ] Anim Cache: Hit 26 ( Soldier 0 )
2016/07/15 23:01:30 DEBUG   [Handle Items    ] Ending bullet, bullets left 0
2016/07/15 23:01:30 DEBUG   [Event Pump      ] AddGameEvent: Sending Local #4
2016/07/15 23:01:30 DEBUG   [Asserts         ] Person got hit, attack count now 2
2016/07/15 23:01:30 DEBUG   [Overhead        ] Ending attack, attack count now 1
2016/07/15 23:01:30 DEBUG   [Asserts         ] Tried to free up attacker, attack count now 1
2016/07/15 23:01:30 DEBUG   [Points          ] Deduct Points (21 at 17827) 4 1139
2016/07/15 23:01:30 DEBUG   [Asserts         ] Chance To Drop Weapon: str: 50 Dam: 38 Chance: -30
2016/07/15 23:01:30 DEBUG   [Event Pump      ] AddGameEvent: Sending Local #4
2016/07/15 23:01:30 DEBUG   [Soldier         ] Opened file (from library ): sounds/bullet impact 01.wav
2016/07/15 23:01:30 DEBUG   [Memory Manager  ] loading file "sounds/bullet impact 01.wav" format 1 channels 1 rate 22050 bits 16 to slot 40
2016/07/15 23:01:30 DEBUG   [Memory Manager  ] playing channel 2 sample 40 file "sounds/bullet impact 01.wav"
2016/07/15 23:01:30 DEBUG   [Memory Manager  ] playing channel 3 sample 15 file "battlesnds/bad0_hit2.wav"
2016/07/15 23:01:30 DEBUG   [Animations      ] Anim Cache: Determining Bump Candidate ( Soldier 21 )
2016/07/15 23:01:30 DEBUG   [Animations      ] Anim Cache: Slot 0 Hits 0 ( Soldier 21 )
2016/07/15 23:01:30 DEBUG   [Animations      ] Anim Cache: Slot 1 Hits 1 ( Soldier 21 )
2016/07/15 23:01:30 DEBUG   [Animations      ] Anim Cache: REJECTING Slot 1 EXISTING ANIM SURFACE ( Soldier 21 )
2016/07/15 23:01:30 DEBUG   [Animations      ] Anim Cache: Bumping 0 ( Soldier 21 )
2016/07/15 23:01:30 DEBUG   [Animations      ] Surface Database: Decrementing Usage 73 ( Soldier 21 )
2016/07/15 23:01:30 DEBUG   [Animations      ] Surface Database: MercUsage: 0, Global Uasage: 3
2016/07/15 23:01:30 DEBUG   [Animations      ] Anim Cache: Loading Surface 8 ( Soldier 21 )
2016/07/15 23:01:30 DEBUG   [Animations      ] Surface Database: Hit 8
2016/07/15 23:01:30 DEBUG   [Animations      ] Surface Database: Incrementing Usage 8 ( Soldier 21 )
2016/07/15 23:01:31 DEBUG   [Memory Manager  ] DEAD channel 2 file "sounds/bullet impact 01.wav" (refcount 1)
2016/07/15 23:01:31 DEBUG   [Points          ] Deduct Points (21 at 17827) 0 0
2016/07/15 23:01:31 DEBUG   [Animations      ] Anim Cache: Hit 25 ( Soldier 21 )
2016/07/15 23:01:31 DEBUG   [Asserts         ] Releasesoldierattacker, normal hit animation ended
													NEW: READY AIM (R) STAND ( 11 ) OLD: GENERIC HIT STAND ( 23 )
2016/07/15 23:01:31 DEBUG   [Asserts         ] Freeing up attacker of 21 (attacker is 0)
													releasesoldierattacker num to free is 1
2016/07/15 23:01:31 DEBUG   [Overhead        ] Ending attack, attack count now 0
Segmentation fault (core dumped)
```

Can someone help with advises?

**Comment by selaux** [comment]
Are you able to provide a backtrace for this? Also: Can you post a screenshot of the fonts looking weird and maybe create a new issue for that?

**Comment by mgrobelin** [comment]
With gdb attached it prints this:

```
[...]
2016/07/16 15:04:50 DEBUG   [Event Pump      ] AddGameEvent: Sending Local #4
2016/07/16 15:04:50 DEBUG   [Asserts         ] Reducing attacker busy count..., CODE FROM ANIMATION SHOOT (R) STAND ( 13 )
2016/07/16 15:04:50 DEBUG   [Overhead        ] Ending attack, attack count now 1
2016/07/16 15:04:50 DEBUG   [Animations      ] Anim Cache: Hit 25 ( Soldier 0 )
2016/07/16 15:04:50 DEBUG   [Handle Items    ] Ending bullet, bullets left 0
2016/07/16 15:04:50 DEBUG   [Event Pump      ] AddGameEvent: Sending Local #4
2016/07/16 15:04:50 DEBUG   [Asserts         ] Person got hit, attack count now 2
2016/07/16 15:04:50 DEBUG   [Morale          ] Handling morale event 4 for IBORG at X=13, Y=3, Z=0
2016/07/16 15:04:50 DEBUG   [Overhead        ] Ending attack, attack count now 1
2016/07/16 15:04:50 DEBUG   [Asserts         ] Tried to free up attacker, attack count now 1
2016/07/16 15:04:50 DEBUG   [Points          ] Deduct Points (22 at 17347) 6 1100
2016/07/16 15:04:50 DEBUG   [Asserts         ] Chance To Drop Weapon: str: 35 Dam: 54 Chance: -11
2016/07/16 15:04:50 DEBUG   [Opp List        ] ManLooksForMan: ID 22(SOLDIER) to ID 0 Personally seen, public 0
2016/07/16 15:04:50 DEBUG   [Opp List        ] ManLooksForMan: ID 22(SOLDIER) to ID 1 Personally seen, public 0
2016/07/16 15:04:50 DEBUG   [Opp List        ] ManLooksForMan: ID 22(SOLDIER) to ID 2 Personally seen, public 0
2016/07/16 15:04:50 DEBUG   [Opp List        ] ManLooksForMan: ID 22(SOLDIER) to ID 3 Personally seen, public 0
2016/07/16 15:04:50 DEBUG   [Event Pump      ] AddGameEvent: Sending Local #4
2016/07/16 15:04:50 DEBUG   [Soldier         ] Opened file (from library ): sounds/bullet impact 02.wav
2016/07/16 15:04:50 DEBUG   [Memory Manager  ] loading file "sounds/bullet impact 02.wav" format 1 channels 2 rate 44100 bits 16 to slot 20
2016/07/16 15:04:50 DEBUG   [Memory Manager  ] halfing the sample rate of "sounds/bullet impact 02.wav" from 44100Hz to 22050Hz
2016/07/16 15:04:50 DEBUG   [Memory Manager  ] playing channel 2 sample 20 file "sounds/bullet impact 02.wav"
2016/07/16 15:04:50 DEBUG   [Animations      ] Anim Cache: Determining Bump Candidate ( Soldier 22 )
2016/07/16 15:04:50 DEBUG   [Animations      ] Anim Cache: Slot 0 Hits 0 ( Soldier 22 )
2016/07/16 15:04:50 DEBUG   [Animations      ] Anim Cache: Slot 1 Hits 3 ( Soldier 22 )
2016/07/16 15:04:50 DEBUG   [Animations      ] Anim Cache: REJECTING Slot 1 EXISTING ANIM SURFACE ( Soldier 22 )
2016/07/16 15:04:50 DEBUG   [Animations      ] Anim Cache: Bumping 0 ( Soldier 22 )
2016/07/16 15:04:50 DEBUG   [Animations      ] Surface Database: Decrementing Usage 73 ( Soldier 22 )
2016/07/16 15:04:50 DEBUG   [Animations      ] Surface Database: MercUsage: 0, Global Uasage: 4
2016/07/16 15:04:50 DEBUG   [Animations      ] Anim Cache: Loading Surface 8 ( Soldier 22 )
2016/07/16 15:04:50 DEBUG   [Animations      ] Surface Database: Loading 8
2016/07/16 15:04:50 DEBUG   [Soldier         ] Opened file (from library ): anims/s_merc/s_diefwd.sti
2016/07/16 15:04:50 DEBUG   [Animations      ] Surface Database: Incrementing Usage 8 ( Soldier 22 )
2016/07/16 15:04:50 DEBUG   [Soldier         ] Opened file (from library ): battlesnds/bad2_die.wav
2016/07/16 15:04:50 DEBUG   [Memory Manager  ] loading file "battlesnds/bad2_die.wav" format 1 channels 1 rate 22050 bits 8 to slot 21
2016/07/16 15:04:50 DEBUG   [Memory Manager  ] playing channel 3 sample 21 file "battlesnds/bad2_die.wav"
2016/07/16 15:04:50 DEBUG   [Points          ] Deduct Points (22 at 17347) 4 250
2016/07/16 15:04:50 DEBUG   [Animations      ] Anim Cache: Hit 8 ( Soldier 22 )
2016/07/16 15:04:51 DEBUG   [Memory Manager  ] DEAD channel 2 file "sounds/bullet impact 02.wav" (refcount 1)
2016/07/16 15:04:51 DEBUG   [Memory Manager  ] DEAD channel 1 file "sounds/weapons/9mm single shot.wav" (refcount 1)
2016/07/16 15:04:51 DEBUG   [Soldier         ] Opened file (from library ): sounds/fall to knees 02.wav
2016/07/16 15:04:51 DEBUG   [Memory Manager  ] loading file "sounds/fall to knees 02.wav" format 1 channels 1 rate 22050 bits 8 to slot 22
2016/07/16 15:04:51 DEBUG   [Memory Manager  ] playing channel 1 sample 22 file "sounds/fall to knees 02.wav"
2016/07/16 15:04:51 DEBUG   [Memory Manager  ] DEAD channel 3 file "battlesnds/bad2_die.wav" (refcount 1)
2016/07/16 15:04:52 DEBUG   [Memory Manager  ] DEAD channel 1 file "sounds/fall to knees 02.wav" (refcount 1)
2016/07/16 15:04:52 DEBUG   [Soldier         ] Opened file (from library ): sounds/knees to dirt 01.wav
2016/07/16 15:04:52 DEBUG   [Memory Manager  ] loading file "sounds/knees to dirt 01.wav" format 1 channels 1 rate 22050 bits 8 to slot 23
2016/07/16 15:04:52 DEBUG   [Memory Manager  ] playing channel 1 sample 23 file "sounds/knees to dirt 01.wav"
2016/07/16 15:04:53 DEBUG   [Animations      ] Anim Cache: Hit 8 ( Soldier 22 )
2016/07/16 15:04:53 DEBUG   [Memory Manager  ] DEAD channel 1 file "sounds/knees to dirt 01.wav" (refcount 1)
2016/07/16 15:04:53 DEBUG   [Morale          ] Handling morale event 0 for IBORG at X=13, Y=3, Z=0
2016/07/16 15:04:53 DEBUG   [Animations      ] Surface Database: Decrementing Usage 8 ( Soldier 22 )
2016/07/16 15:04:53 DEBUG   [Animations      ] Surface Database: MercUsage: 0, Global Uasage: 0
2016/07/16 15:04:53 DEBUG   [Animations      ] Surface Database: Unloading Surface: 8
2016/07/16 15:04:53 DEBUG   [Animations      ] Surface Database: Decrementing Usage 25 ( Soldier 22 )
2016/07/16 15:04:53 DEBUG   [Animations      ] Surface Database: MercUsage: 0, Global Uasage: 1
2016/07/16 15:04:53 DEBUG   [Animations      ] Removing Anim Cache surface for soldier 22
2016/07/16 15:04:53 DEBUG   [Animations      ] Removing Anim Cache hit counter for soldier 22
2016/07/16 15:04:53 DEBUG   [Asserts         ] Releasesoldierattacker, code 497 = handle soldier death
2016/07/16 15:04:53 DEBUG   [Asserts         ] Freeing up attacker of 22 (attacker is 0)
													releasesoldierattacker num to free is 1
2016/07/16 15:04:53 DEBUG   [Overhead        ] Ending attack, attack count now 0
2016/07/16 15:04:53 DEBUG   [Soldier         ] Opened file (from library ): battlesnds/052_cool.wav
2016/07/16 15:04:53 DEBUG   [Memory Manager  ] loading file "battlesnds/052_cool.wav" format 17 channels 1 rate 22050 bits 4 to slot 24
2016/07/16 15:04:53 DEBUG   [Memory Manager  ] playing channel 1 sample 24 file "battlesnds/052_cool.wav"

Thread 1 "ja2" received signal SIGSEGV, Segmentation fault.
0x00007ffff68d79f0 in wcslen () from /lib64/libc.so.6

(gdb) bt
#0  0x00007ffff68d79f0 in wcslen () from /lib64/libc.so.6
#1  0x00007ffff6887414 in vfwprintf () from /lib64/libc.so.6
#2  0x00007ffff689e805 in vswprintf () from /lib64/libc.so.6
#3  0x00007ffff689e4d2 in swprintf () from /lib64/libc.so.6
#4  0x00000000005c1fb6 in BuildStatChangeString(wchar_t*, unsigned long, wchar_t const*, unsigned char, short, StatKind) ()
#5  0x00000000005c2a19 in ChangeStat(MERCPROFILESTRUCT&, SOLDIERTYPE*, StatKind, short) ()
#6  0x00000000005c2fcb in ProcessUpdateStats(MERCPROFILESTRUCT&, SOLDIERTYPE*) [clone .part.5] ()
#7  0x00000000005c3b52 in HandleAnyStatChangesAfterAttack() ()
#8  0x000000000063f9e8 in InternalReduceAttackBusyCount(SOLDIERTYPE*, unsigned char, SOLDIERTYPE*)
    ()
#9  0x0000000000665b8e in ReleaseSoldiersAttacker(SOLDIERTYPE*) ()
#10 0x000000000065e91b in CheckForAndHandleSoldierDeath(SOLDIERTYPE*, unsigned char*) ()
#11 0x000000000065fe8d in AdjustToNextAnimationFrame(SOLDIERTYPE*) ()
#12 0x0000000000640848 in ExecuteOverhead() ()
#13 0x0000000000726b3e in MainGameScreenHandle() ()
#14 0x0000000000725095 in GameLoop() ()
#15 0x00000000004975c2 in main ()
(gdb) quit
A debugging session is active.

	Inferior 1 [process 6655] will be killed.

Quit anyway? (y or n) y
```

**Comment by selaux** [comment]
This does not seem to be related to SDL2. Can you also reproduce it with current master?

**Comment by selaux** [comment]
Can you provide a savegame of when it is gonna happen?
