### ISSUE TITLE
Another blitter crash

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#382]
```
Thread 1 "ja2" received signal SIGSEGV, Segmentation fault.
0x000000000081c3f3 in Blt8BPPDataTo16BPPBufferTransZNBClipTranslucent (buf=0x7ffff16b8010, 
    uiDestPitchBYTES=1280, zbuf=0x7fffec61e010, zval=11806, hSrcVObject=0x1fdde50, iX=476, iY=12, 
    usIndex=1, clipregion=0xfba284 <g_ui+196>)
    at /home/kajak/games/ja2-stracciatella/sgp/VObject_Blitters.cc:141
141                                                     (*dst      >> 1 & translucent_mask);
(gdb) bt
#0  0x000000000081c3f3 in Blt8BPPDataTo16BPPBufferTransZNBClipTranslucent (buf=0x7ffff16b8010, 
    uiDestPitchBYTES=1280, zbuf=0x7fffec61e010, zval=11806, hSrcVObject=0x1fdde50, iX=476, iY=12, 
    usIndex=1, clipregion=0xfba284 <g_ui+196>)
    at /home/kajak/games/ja2-stracciatella/sgp/VObject_Blitters.cc:141
#1  0x000000000079441a in RenderTiles (uiFlags=TILES_NONE, iStartPointX_M=76, iStartPointY_M=119, 
    iStartPointX_S=-40, iStartPointY_S=-50, iEndXS=680, iEndYS=400, ubNumLevels=5 '\005', 
    psLevelIDs=0x7fffffffb860)
    at /home/kajak/games/ja2-stracciatella/Build/TileEngine/RenderWorld.cc:1334
#2  0x00000000007964c2 in RenderDynamicWorld ()
    at /home/kajak/games/ja2-stracciatella/Build/TileEngine/RenderWorld.cc:1958
#3  0x000000000079582e in RenderWorld ()
```
Again while trying to reproduce something else. Happened on a normal enemy turn while I was afk (heard a mortar though). Just throwing it here in case it is hit again. I'll check if any of the coverity beeps is relevant.

**Comment by derSteFfi** [comment]
hm. the function wasn't touched in a while. fix Wnarrowing changed some types though. I currently don't have the time to track it down, but maybe you should try to reproduce this and if you can reproduce it, try before Wnarrowing...
