### ISSUE TITLE
libstracciatella failing to build in VS15

### ISSUE THREAD

**Issue by arnodick** [ja2-stracciatella/ja2-stracciatella#749]
### What is wrong
When building libstracciatella in Visual Studio 15 some crates fail to build due to missing references.

I made the following changes to fix missing references:
rust\src\config\ja2_json.rs - added at line 1
```
#[macro_use]
extern crate num_derive;
extern crate num_traits;

use num_traits::FromPrimitive;
```
rust\Cargo.toml - added num-traits = "0.2" and num-derive = "0.2" under [dependencies]
```
[dependencies]
getopts = "0.2.15"
libc = "0.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
dirs = "1"
num-traits = "0.2"
num-derive = "0.2"
```

rust\src\stracciatella.rs - added at line 1
`#[macro_use]`

Unfortunately it's now giving an error I can't solve:

```
CUSTOMBUILD : error : failed to run custom build command for `stracciatella v0.1.0 (file:///J:/rust)` [J:\_bin\libstracciatella-prefix\src\libstracciatella-build\rust-build.vcxproj]
  process didn't exit successfully: `J:/_bin/libstracciatella-prefix/src/libstracciatella-build/rust\release\build\stracciatella-98fcdf95f476b2be\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to generate bindings: ParseSyntaxError { crate_name: "stracciatella", src_path: "J:\\rust\\src/stracciatella.rs", error: ParseError(Some("failed to parse crate: failed to parse anything")) }', libcore\result.rs:945:5
  stack backtrace:
     0: <std::sync::mpsc::RecvTimeoutError as core::fmt::Debug>::fmt
     1: <std::sys::windows::dynamic_lib::DynamicLibrary as core::ops::drop::Drop>::drop
     2: std::panicking::take_hook
     3: std::panicking::take_hook
     4: std::panicking::rust_panic_with_hook
     5: std::panicking::begin_panic_fmt
     6: rust_begin_unwind
     7: core::panicking::panic_fmt
     8: core::result::unwrap_failed<cbindgen::bindgen::error::Error>
               at C:\projects\rust\src\libcore\macros.rs:26
     9: build_script_build::main
               at .\build.rs:17
    10: std::rt::lang_start::{{closure}}<()>
               at C:\projects\rust\src\libstd\rt.rs:74
    11: std::panicking::update_panic_count
    12: _rust_maybe_catch_panic
    13: std::rt::lang_start_internal
    14: main
    15: __scrt_common_main_seh
               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    16: BaseThreadInitThunk
    17: RtlUserThreadStart

Done Building Project "J:\_bin\libstracciatella-prefix\src\libstracciatella-build\rust-build.vcxproj" (default targets) -- FAILED.
Done Building Project "J:\_bin\libstracciatella-prefix\src\libstracciatella-build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"J:\_bin\libstracciatella-prefix\src\libstracciatella-build\ALL_BUILD.vcxproj" (default target) (1) ->
"J:\_bin\libstracciatella-prefix\src\libstracciatella-build\rust-build.vcxproj" (default target) (3) ->
(CustomBuild target) ->
CUSTOMBUILD : error : failed to run custom build command for `stracciatella v0.1.0 (file:///J:/rust)` [J:\_bin\libstracciatella-prefix\src\libstracciatella-build\rust-build.vcxproj]

```

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git | eg. JA2 Gold English  |    no    |    ?     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
Windows 7

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by selaux** [comment]
```
#[macro_use]
extern crate num_derive;
extern crate num_traits;
```

This always belongs into the top level module (`stracciatella.rs` in this case), maybe that helps. What missing references were you trying to resolve?

**Comment by selaux** [comment]
Are you using the most recent stable rust verision (1.30.1)?

**Comment by arnodick** [comment]
Ah, of course! A silly mistake.

After updating rust and cleaning and rebuilding it seems to be building fine. The num-traits and num-derive references aren't needed any more.
